name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: cloudlogpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, mysql
          coverage: xdebug
      - name: Start Apache
        run: sudo service apache2 start
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          command-prefix: "--headless --browser edge"
          wait-on: "http://localhost"
