name: ci

#on:
#  push:
#    branches:
#      - "main"

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: findtag  # The step ID to refer to later.
        with:
          #repository: octokit/rest.js  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
      - name: Print latest tag
        run: echo ${{ steps.findtag.outputs.tag }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGENAME }}:${{ steps.findtag.outputs.tag }}
